// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OHunt.Web.Data;

namespace OHunt.Web.Migrations
{
    [DbContext(typeof(OHuntWebContext))]
    [Migration("20200701054200_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("OHunt.Web.Models.Submission", b =>
                {
                    b.Property<long>("SubmissionId")
                        .HasColumnType("bigint");

                    b.Property<int>("OnlineJudgeId")
                        .HasColumnType("int");

                    b.HasKey("SubmissionId", "OnlineJudgeId");

                    b.ToTable("submissions");
                });
#pragma warning restore 612, 618
        }
    }
}
