// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OHunt.Web.Database;

namespace OHunt.Web.Migrations
{
    [DbContext(typeof(OHuntWebContext))]
    [Migration("20200702142254_AddCrawlerError")]
    partial class AddCrawlerError
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("OHunt.Web.Models.CrawlerError", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Crawler")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Data")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("CrawlerError");
                });

            modelBuilder.Entity("OHunt.Web.Models.Submission", b =>
                {
                    b.Property<long>("SubmissionId")
                        .HasColumnType("bigint");

                    b.Property<int>("OnlineJudgeId")
                        .HasColumnType("int");

                    b.Property<string>("ProblemLabel")
                        .IsRequired()
                        .HasColumnType("varchar(25) CHARACTER SET utf8mb4")
                        .HasMaxLength(25);

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(75) CHARACTER SET utf8mb4")
                        .HasMaxLength(75);

                    b.HasKey("SubmissionId", "OnlineJudgeId");

                    b.HasIndex("Status");

                    b.HasIndex("UserName");

                    b.ToTable("submissions");
                });
#pragma warning restore 612, 618
        }
    }
}
