// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OHunt.Web.Database;

namespace OHunt.Web.Migrations
{
    [DbContext(typeof(OHuntDbContext))]
    [Migration("20210627092639_UpgradeDriver")]
    partial class UpgradeDriver
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("OHunt.Web.Models.CrawlerError", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Crawler")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Data")
                        .HasColumnType("longtext");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("CrawlerError");
                });

            modelBuilder.Entity("OHunt.Web.Models.ProblemLabelMapping", b =>
                {
                    b.Property<long>("ProblemId")
                        .HasColumnType("bigint");

                    b.Property<int>("OnlineJudgeId")
                        .HasColumnType("int");

                    b.Property<string>("ProblemLabel")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.HasKey("ProblemId", "OnlineJudgeId");

                    b.ToTable("problem_label_mappings");
                });

            modelBuilder.Entity("OHunt.Web.Models.Submission", b =>
                {
                    b.Property<long>("SubmissionId")
                        .HasColumnType("bigint");

                    b.Property<int>("OnlineJudgeId")
                        .HasColumnType("int");

                    b.Property<string>("ProblemLabel")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("varchar(75)");

                    b.HasKey("SubmissionId", "OnlineJudgeId");

                    b.HasIndex("Status");

                    b.HasIndex("UserName");

                    b.ToTable("submissions");
                });
#pragma warning restore 612, 618
        }
    }
}
