pull_request_rules:
  - name: automatic merge on CI success and tag
    conditions:
      - "#status-failure=0"
      - "#status-neutral=0"
      - "#status-success>0"
      - label=ready-to-be-merged
    actions:
      merge:
        method: rebase
        # rebase_fallback: merge
        strict: smart
