rules:
  default:
    protection:
      required_status_checks:
        strict: false
        contexts:
          - continuous-integration/travis-ci
          - mergify/future-config-checker
          - WIP
      required_pull_request_reviews:
        required_approving_review_count: 1
        require_code_owner_reviews: true
        dismiss_stale_reviews: true
    merge_strategy:
      method: rebase
    disabling_label: dependencies
