rules:
  default:
    protection:
      required_status_checks:
        strict: false
        contexts:
          - continuous-integration/travis-ci
          - mergify/future-config-checker
          - codecov
          - WIP
      required_pull_request_reviews:
        required_approving_review_count: 0
        dismiss_stale_reviews: true
    merge_strategy:
      method: rebase
    enabling_label: ready-to-be-merged
