pull_request_rules:
  - name: automatic merge on CI success and tag
    conditions:
      # Github Action 只接收job名称
      # 测试所有以Test开头的job
      - "status-success~=^Test: "
      - status-success=WIP
      - label=ready-to-be-merged
    actions:
      merge:
        method: rebase
        # rebase_fallback: merge
        strict: smart
