rules:
  default:
    protection:
      required_status_checks:
        strict: false
        contexts:
          - continuous-integration/travis-ci
          - codecov/project
          - WIP
      required_pull_request_reviews: null
    merge_strategy:
      method: rebase
    enabling_label: ready-to-be-merged
