pull_request_rules:
  - name: automatic merge on CI success and tag
    conditions:
      - label=ready-to-be-merged
    actions:
      merge:
        method: rebase
        # rebase_fallback: merge
        strict: smart
