pull_request_rules:
  - name: automatic merge on CI success and tag
    conditions:
      - status-success~=^Integration Test
      - status-success~=^Test E2E
      - status-success=WIP
      - label=ready-to-be-merged
    actions:
      merge:
        method: rebase
        # rebase_fallback: merge
        strict: smart
