ignore:
  - backend/src/AcmStatisticsBackend.EntityFrameworkCore/**/*
  - backend/src/AcmStatisticsBackend.Migrator/**/*
  - backend/src/AcmStatisticsBackend.Web.Core/**/*
  - backend/src/AcmStatisticsBackend.Web.Host/**/*
