crawler_order:
  - poj
  - hdu
  - zoj
  - dashiye
  - codeforces
  - uva
  - uvalive
  - fzu
  - spoj
  - timus
  - leetcode_cn
  - csu
  - loj
  - luogu
  - nowcoder
  - uestc
  - atcoder
  - aizu
  - codechef
  - eljudge
  - bnu
  - codewars
  - uoj
  - nbut
  - nod
  # - nit
  - dmoj
  - vjudge

crawlers:
  poj:
    meta:
      title: POJ
      description:
      url: http://poj.org/
  hdu:
    meta:
      title: HDU
      description:
      url: http://acm.hdu.edu.cn/
  zoj:
    meta:
      title: ZOJ
      description: Only nickname is supported (Only historical data are available since crawlers are prohibited by Pintia)
      url: https://zoj.pintia.cn/
  dashiye:
    meta:
      title: HYSBZ
      description:
      url: http://www.lydsy.com/JudgeOnline/
  codeforces:
    meta:
      title: CodeForces
      description: Including CodeForces::Gym
      url: http://codeforces.com/
  uva:
    meta:
      title: UVA
      description:
      url: https://uva.onlinejudge.org/
  uvalive:
    meta:
      title: ICPC Live Archive
      description:
      url: https://icpcarchive.ecs.baylor.edu/index.php
  fzu:
    meta:
      title: FZU
      description:
      url: http://acm.fzu.edu.cn/index.php
  spoj:
    meta:
      title: SPOJ
      description:
      url: http://www.spoj.com/
  timus:
    meta:
      title: Timus (URAL)
      description:
      url: http://acm.timus.ru/
  leetcode_cn:
    meta:
      title: LeetCode_CN
      description:
      url: https://leetcode-cn.com
  csu:
    meta:
      title: CSU
      description:
      url: http://acm.csu.edu.cn/
  loj:
    meta:
      title: LibreOJ
      description:
      url: https://loj.ac/
  luogu:
    meta:
      title: 洛谷
      description:
      url: https://www.luogu.com.cn
  nowcoder:
    meta:
      title: 牛客OJ
      description: 目前只支持输入用户ID（在你的AC列表的URL中）
      url: https://ac.nowcoder.com/acm/home
  uestc:
    meta:
      title: Lutece (UESTC)
      description:
      url: https://acm.uestc.edu.cn/home
  atcoder:
    meta:
      title: AtCoder
      description: |
        API provided by kenkoooo (https://github.com/kenkoooo/AtCoderProblems).
        It may take a while for the api to update user statistics.
      url: https://atcoder.jp
  aizu:
    meta:
      title: AIZU
      description:
      url: http://judge.u-aizu.ac.jp/onlinejudge/index.jsp
  codechef:
    meta:
      title: CodeChef
      description:
      url: https://www.codechef.com/
  eljudge:
    meta:
      title: El Judge
      description:
      url: http://acm.mipt.ru
  bnu:
    meta:
      title: BNUOJ
      description:
      url: http://www.bnuoj.com
  codewars:
    meta:
      title: Codewars
      description: |
        Currently it does not have submission number.
        Username is case sensitive.
      url: https://www.codewars.com
  uoj:
    meta:
      title: UOJ
      description:
      url: http://uoj.ac/
  nbut:
    meta:
      title: NBUT
      description:
      url: https://ac.2333.moe/
  nod:
    meta:
      title: 51Nod
      description: Please use your nickname (displayed in your home page)
      url: https://www.51nod.com
  nit:
    meta:
      title: OurOJ (NIT)
      description:
      url: https://www.nitacm.com/
  dmoj:
    meta:
      title: DMOJ
      description:
      url: https://dmoj.ca/
  vjudge:
    meta:
      title: VJudge
      description: virtual judge，这个OJ的题量是单独计算的
      url: https://vjudge.net/
      virtual_judge: true
    # 只运行在服务器上，不运行在浏览器上
    server_only: true
    # vjudge 有一个api接口，需要用任意的用户名和密码来接入才能访问
    crawler_login_user: 用户名
    crawler_login_password: 密码
