crawler_order:
  - poj
  - hdu
  - zoj
  - dashiye
  - codeforces
  - uva
  - fzu
  - spoj
  - timus
  - sgu
  - leetcode_cn
  - csu
  - vjudge

crawlers:
  poj:
    meta:
      title: POJ
      description:
      url: http://poj.org/
  hdu:
    meta:
      title: HDU
      description:
      url: http://acm.hdu.edu.cn/
  zoj:
    meta:
      title: ZOJ
      description:
      url: http://acm.zju.edu.cn/onlinejudge/
  dashiye:
    meta:
      title: 大视野在线测评
      description:
      url: http://www.lydsy.com/JudgeOnline/
  codeforces:
    meta:
      title: CodeForces
      description:
      url: http://codeforces.com/
  uva:
    meta:
      title: UVA
      description:
      url: https://uva.onlinejudge.org/
  fzu:
    meta:
      title: FZU
      description:
      url: http://acm.fzu.edu.cn/index.php
  spoj:
    meta:
      title: SPOJ
      description:
      url: http://www.spoj.com/
  timus:
    meta:
      title: Timus
      description:
      url: http://acm.timus.ru/
  sgu:
    meta:
      title: SGU
      description: SGU允许多个用户有相同的名字（ID不同），本爬虫会选择在 http://acm.sgu.ru/find.php?find_id= 中出现的第一个
      url: http://acm.sgu.ru/
  leetcode_cn:
    meta:
      title: LeetCode（中国）
      description:
      url: https://leetcode-cn.com
  csu:
    meta:
      title: CSU
      description:
      url: http://acm.csu.edu.cn/
  vjudge:
    meta:
      title: VJudge
      description: virtual judge，这个OJ的题量是单独计算的
      url: https://vjudge.net/
    # 只运行在服务器上，不运行在浏览器上
    server_only: true
    # vjudge 有一个api接口，需要用任意的用户名和密码来接入才能访问
    crawler_login_user: 用户名
    crawler_login_password: 密码
