name: Test crawler availability (can be inaccurate)

on: 
  schedule:
  # at noon
  - cron: 0 12 * * *

jobs:

  crawler-check:
    runs-on: ubuntu-latest
    env:
      'ACM_STATISTICS_CRAWLER_ENV:crawlers:vjudge:crawler_login_user': ${{ secrets.VJUDGE_USERNAME }}
      'ACM_STATISTICS_CRAWLER_ENV:crawlers:vjudge:crawler_login_password': ${{ secrets.VJUDGE_PASSWORD }}
    steps:
    - uses: actions/checkout@master
    - run: |
        cd crawler
        npm install
        npm test -- --forceExit --ci
