name: auto deploy on master

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: 'Checkout'
      uses: 'actions/checkout@v1'

    - name: 'Wait for status checks'
      id: check
      uses: "WyriHaximus/github-action-wait-for-status@v2"
      with:
        ignoreActions: codecov/project,codecov/patch,deploy
        checkInterval: 60
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

    - name: 'Deploy ${{ github.event.deployment.environment }}'
      if: steps.check.outputs.status == 'success'
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        make tag-and-push