name: auto deploy on master

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: Wait for status checks
      id: check
      uses: WyriHaximus/github-action-wait-for-status@v1.4
      with:
        ignoreActions: codecov/project,codecov/patch,deploy,E2E on pull request,update-snapshot,Update HTML Snapshot when comment on pr,Update E2E Snapshot when comment on pr,crawler-check,检查爬虫可用性（不准确）
        checkInterval: 60
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

    - name: Deploy
      if: steps.check.outputs.status == 'success'
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        make tag-and-push
        
    - name: Failed
      if: steps.check.outputs.status != 'success'
      run: |
        echo deploy check status "${{ steps.check.outputs.status }}"
        exit 1
