name: 部署主分支

on:
  push:
    branches:
      - master

jobs:
  deploy-master:
    name: 部署主分支
    runs-on: ubuntu-latest
    steps:
    - name: Wait for status checks
      id: waitforstatuschecks
      uses: WyriHaximus/github-action-wait-for-status@master
      with:
        checkInterval: 60
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    - uses: actions/checkout@master
      if: steps.waitforstatuschecks.outputs.status == 'success'
    - name: Deploy master
      if: steps.waitforstatuschecks.outputs.status == 'success'
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        make tag-and-push
