name: Test E2E on pull request

on: pull_request

jobs:
  e2e-pr:
    name: E2E on pull request
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: |
        cd e2e
        echo ::group::build
        make server compose-args="--detach"
        make wait-server
        echo ::endgroup::build
        make ci-no-record
        make run run-cmd="npm run lint" make-args="no-interactive no-tty"
    - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3
      if: failure()
      with:
        name: e2e-screenshots
        path: e2e/cypress/screenshots
    - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3
      if: failure()
      with:
        name: e2e-snapshots
        path: e2e/cypress/snapshots
    - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3
      if: failure()
      with:
        name: e2e-videos
        path: e2e/cypress/videos
